### ISSUE TITLE
Syntactic Tail Calls (STC)

### ISSUE THREAD

**Issue by leobalter** [jquery-foundation/standards#30]
TC39 is currently discussing [STC](https://github.com/tc39/proposal-ptc-syntax) as an alternative solution to [ES2015 Proper Tail Calls](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-tail-position-calls).

https://github.com/tc39/proposal-ptc-syntax

Here is a summary of what's happening:

This proposal involves including a new syntax to indicate whether a function is using Tail Call Optimization or not. That solves some implementation problems like performance and the fact it can [expose security issues on Firefox](https://github.com/tc39/tc39-notes/blob/4d5fb147e6b714f682aaf5da803ca14ec5fb3b82/es7/2016-03/march-29.md#tco) the way it's implemented. The alternative suggested by some runtime implementors is removing the Tail Call Optimization in a next spec version, which sounds bad.

It's worth mentioning this feature came pre-[staging process](http://tc39.github.io/process-document/) and it was released before it was implemented in any major runtime. Today that would require at least two runtimes to implement it before it reaches stage 4, where it becomes part of the specs.

My ideas on this proposal are mostly in sync with @getify, as the first desirable option is [not adding any new syntax for it](https://github.com/tc39/proposal-ptc-syntax/issues/1#issuecomment-209162923).

There's a strong resistance from Apple JSC against accepting and adopting STC](https://github.com/tc39/ecma262/issues/535).

---

This issue is just informative, discussions on the future of the proposal should be handled on the [proposal's repo](https://github.com/tc39/proposal-ptc-syntax). We can still use this issue for minor discussions, like: "what is tail call optimization?" or "what is proper tail calls?".

**Comment by getify** [comment]
For posterity:

> what is proper tail calls?

Referred to as PTC, proper tail calls mean that a function call in a "proper tail call" position -- that is, something like `return foo(x - 1)`, where the only thing left to do after the function call finishes is return its return value.

Imagine this code:

```js
function foo(x) {
   if (x == 0) return x;
   return foo(x - 1);
}
```

Obviously, it's silly/trivial (in that it clearly just recurses until it returns `0`). This code makes a function call (`foo(x - 1)`), and it happens to do so in a PTC position. Normally, that function call would require a new stack frame (allocation of memory), meaning that if this recursion ran thousands of levels deep, memory could eventually run out. That linear memory usage is the primary limitation that's prevented most recursive patterns from being popular/generally applicable in JS.

Though the spec says nothing about it, all engines (AFAIK) implement a limit as to how deep they'll let a call stack go before they throw an error to stop it (typically: `RangeError: maximum call stack depth reached`) to prevent a runaway memory consumption and device crash condition.

The big deal about PTCs is that they can actually be made in such a way that no additional stack space needs to be allocated for the tail call's stack frame. To do this, engines can basically reuse the current stack frame (since it's not needed anymore). That means the memory usage of an arbitrarily deep call stack remains O(1) constant, which means recursion could run as long as you'd like it to.

**Note:** PTC is often thought of in terms of recursion but it's actually generalized to any function that calls another function (assuming it's in the PTC form position). But it's exceedingly rare that you'd have a call-stack depth of more than a couple dozen calls at most, if you weren't doing recursion; and at that small depth, memory usage is usually not a concern.

It's important to point out that many in the JS standards space bristle at calling this PTC stuff an "optimization", as that word is usually thought of in terms of speeding up code. PTC is only about limiting memory usage, but in some cases (and some engines), such calls might run a little bit slower in exchange for the constant memory usage.

> what is tail call optimization?

Referred to as TCO (and also extremely commonly confused with PTC), tail call optimization refers to a set of additional techniques that an engine can layer on top of tail calls to optimize things even further.

PTC is required by the ES2015 spec (for conforming tail calls). TCO is not, but is implicitly left optional to each implementation.

**Comment by leobalter** [comment]
Thank you, Kyle! You saved me a time describing PTC and TCO and you did it great!

**Comment by gnarf** [comment]
> It's important to point out that many in the JS standards space bristle at calling this PTC stuff an "optimization", as that word is usually thought of in terms of speeding up code. PTC is only about limiting memory usage, but in some cases (and some engines), such calls might run a little bit slower in exchange for the constant memory usage.

extra 😍

**Comment by leobalter** [comment]
> in some cases (and some engines), such calls might run a little bit slower in exchange for the constant memory usage.

I might be wrong as I don't remember it well, but I think someone from JSC saying the PTC didn't improve anything in performance, as it was expected by some people.

**Comment by leobalter** [comment]
I can provide more details, but after __7 hours__ debating on these topics, TC39 didn't advance on anything related to STC or PTC.

Apple has implemented TCO per spec text and doesn't want to remove it.
Google has implemented TCO under a flag and is flexible to consider changes
Mozilla and MS haven't implemented TCO due to technical incompatibilities and security concerns as they proposed STC.

The main "named" concerns to implement for TCO are cross realm leaks and poor information for Error.stack and debugging JS code. MS has also an implementation incompatibility on their x64 build.

My own opinions: STC is a radical change and I'm not sure it address the concerns. A proposal to directly fix the cross realm leaks seems reasonable, but that's not happening for now. The Error.stack is a non-(ecma)standard feature and this is a more hard to fix within ES specs.

The other proposal, out of the agenda, was removing TCO entirely from the specs.

Every idea found objections from every part, and it seems TC39 will need to spend more time and meetings discussing it.

**Comment by ljharb** [comment]
`s/TCO/PTC/g`

**Comment by leobalter** [comment]
done with the replacement, but still:

> The other proposal, out of the agenda, was removing PTC entirely from the specs.

Is also valid as:

> The other proposal, out of the agenda, was removing TCO entirely from the specs.

:)

**Comment by ljharb** [comment]
TCO isn't in the spec, so there'd be nothing to remove :-) Everyone has always been free to apply TCO, and will always be.

**Comment by leobalter** [comment]
Well, PTC is the only explicit form of TCO in the specs. :)

Otherwise, there's no other way to say recursive calls are memory
optimized.

**Comment by leobalter** [comment]
Apparently this won't have any other change in the specs. I'll close it for now.
